"""add_contact_fields_and_contact_meeting_links

Revision ID: c85ad30d08de
Revises: 6298a0455a0c
Create Date: 2026-05-24 16:49:24.081789
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c85ad30d08de'
down_revision: Union[str, None] = '6298a0455a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_meeting_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_meeting_links_contact_id'), 'contact_meeting_links', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_meeting_links_meeting_id'), 'contact_meeting_links', ['meeting_id'], unique=False)
    op.add_column('contacts', sa.Column('phone', sa.String(length=40), nullable=True))
    op.add_column('contacts', sa.Column('title', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'notes')
    op.drop_column('contacts', 'title')
    op.drop_column('contacts', 'phone')
    op.drop_index(op.f('ix_contact_meeting_links_meeting_id'), table_name='contact_meeting_links')
    op.drop_index(op.f('ix_contact_meeting_links_contact_id'), table_name='contact_meeting_links')
    op.drop_table('contact_meeting_links')
    # ### end Alembic commands ###
